const assert=require('node:assert/strict');
const fs=require('node:fs');
const {loadFundFees,buildFundFees,selectFee}=require('../scripts/fund-fees');
const data=JSON.parse(fs.readFileSync(require('node:path').join(__dirname,'../data/fund-fees.json'),'utf8'));
assert.deepEqual(buildFundFees(),data,'Normalized fee file must reproduce from source observations');
assert.ok(data.coverage.percent>90);
const fees=loadFundFees();
assert.equal(data.coverage.accepted,1995);assert.equal(data.coverage.universe,2104);
for(const [symbol,rate] of Object.entries({VSCPX:0.02,NAESX:0.17,VSIAX:0.07,VTMGX:0.05,VQNPX:0.4,VVIAX:0.05,BLV:0.03,DFLVX:0.22,DLS:0.58,RPV:0.35,ARKK:0.75,AVDV:0.36,AGTHX:0.59}))assert.equal(fees[symbol].expenseRatio,rate,symbol);
for(const symbol of ['GOF','EAD','VCX'])assert.equal(fees[symbol],undefined,'NAV-based fee must not use market-value multiplication');
assert.equal(fees.VTI.expenseRatio,0.03);
assert.equal(fees.FZROX.expenseRatio,0);
assert.equal(fees.SPY.expenseRatio,0.0945);
for(const symbol of ['BTC','ETH','AGG','PONAX','BNO','IAU'])assert.equal(fees[symbol],undefined,symbol+' must remain unknown until reconciled');
const record={status:'candidate',retrievedOn:'2026-10-05',source:'https://issuer.example/fund'};
assert.ok(selectFee({...record,sponsorFeePct:0.2}).reason);
assert.ok(selectFee({...record,netPct:0.2,grossPct:0.1}).reason);
assert.ok(selectFee({...record,netPct:0.1,waiverExpiresOn:'2026-09-01'}).reason);
assert.ok(selectFee({...record,grossPct:0.1,note:'Temporary fee waiver applies'}).reason);
assert.ok(selectFee({...record,netPct:0.1,asOf:'2027-01-01'}).reason);
assert.equal(selectFee({...record,netPct:0,grossPct:0.1}).fee.expenseRatio,0);
assert.equal(selectFee({...record,expenseRatioPct:0.1}).fee.basis,'issuer-total');
assert.equal(selectFee({...record,grossPct:0.1}).fee.basis,'gross');
assert.equal(selectFee({...record,netPct:0.1}).fee.asOf,null,'Retrieval date must not masquerade as effective date');
console.log('Fund fee normalization and issuer sample checks passed: '+data.coverage.accepted+'/'+data.coverage.universe);
