/* Build-time only: the app never fetches the catalog at runtime. */
const fs = require('node:fs');
const path = require('node:path');
const root = path.join(__dirname, '..');
const marker = '/* INSTRUMENT_CATALOG: generated by scripts/instrument-catalog.js */';
const classes = new Set(['us_large', 'us_mid', 'us_small', 'us_total', 'intl_dev', 'em', 'us_bond', 'intl_bond', 'reit', 'commod', 'crypto', 'cash', 'blend', 'other']);
const own = (o, k) => Object.prototype.hasOwnProperty.call(o, k);
function requireThat(condition, message) { if (!condition) throw new Error(`Instrument catalog: ${message}`); }
function coverage(values, universe) {
  const symbols = [...new Set(universe)];
  const missing = symbols.filter(symbol => !own(values, symbol) || values[symbol] == null);
  return { total: symbols.length, populated: symbols.length - missing.length, missing, ratio: symbols.length ? (symbols.length - missing.length) / symbols.length : 0 };
}
function validateCatalog(catalog) {
  requireThat(catalog.schemaVersion === 1, 'unsupported schema');
  requireThat(Array.isArray(catalog.instruments) && catalog.instruments.length > 0, 'empty instrument list');
  const seen = new Set();
  const recordKeys = new Set(['symbol', 'assetClass', 'reviewNote', 'reviewedOn', 'source', 'name', 'identitySource', 'identityReviewedOn']);
  for (const record of catalog.instruments) {
    requireThat(Object.keys(record).every(k => recordKeys.has(k)), 'new fields need a coverage and correctness audit before enabling');
    requireThat(typeof record.symbol === 'string' && /^[A-Z0-9][A-Z0-9._-]*$/.test(record.symbol), 'invalid symbol');
    requireThat(!seen.has(record.symbol), `duplicate ${record.symbol}`);
    seen.add(record.symbol);
    if (record.name !== undefined) {
      requireThat(typeof record.name === 'string' && record.name.trim().length > 0 && record.name.length < 250, `invalid name for ${record.symbol}`);
      requireThat(/^https:\/\//.test(record.identitySource || '') && /^\d{4}-\d{2}-\d{2}$/.test(record.identityReviewedOn || ''), `missing identity provenance for ${record.symbol}`);
    }
    requireThat(record.assetClass === null || classes.has(record.assetClass), `invalid class for ${record.symbol}`);
    requireThat(record.assetClass !== null || (typeof record.reviewNote === 'string' && record.reviewNote.length > 0), `missing review guidance for ${record.symbol}`);
    if (record.source || record.reviewedOn || record.reviewNote) {
      requireThat(typeof record.source === 'string' && /^https:\/\//.test(record.source), `missing source for ${record.symbol}`);
      requireThat(/^\d{4}-\d{2}-\d{2}$/.test(record.reviewedOn || ''), `missing review date for ${record.symbol}`);
    }
  }
  requireThat(Array.isArray(catalog.enabledFields) && catalog.enabledFields.every(f => f === 'name'), 'unsupported enabled field');
  if (catalog.enabledFields.includes('name')) {
    const audit = JSON.parse(fs.readFileSync(path.join(root, 'data/instrument-audit.json'), 'utf8'));
    const universe = new Set(audit.fundUniverse);
    requireThat([...universe].every(s => seen.has(s)), 'fund universe contains missing catalog symbols');
    const names = Object.fromEntries(catalog.instruments.filter(r => r.name).map(r => [r.symbol, r.name]));
    requireThat(coverage(names, [...universe]).ratio > 0.9, 'fund names must exceed 90% coverage');
  }
  const split = catalog.usTotalSplit;
  requireThat(split && Object.keys(split).length === 3 && ['us_large', 'us_mid', 'us_small'].every(k => Number.isFinite(split[k]) && split[k] >= 0), 'invalid total-market split');
  requireThat(Math.abs(Object.values(split).reduce((a, b) => a + b, 0) - 100) < 1e-9, 'total-market split must sum to 100');
  const numeric = new Set(['divYield', 'qualifiedPct', 'capGainDistPct', 'usGovtPct']);
  const flags = new Set(['ftcEligible', 'qbiEligible', 'muni', 'collectible', 'sixtyForty']);
  requireThat(catalog.taxAssumptions && typeof catalog.taxAssumptions === 'object', 'missing tax assumptions');
  for (const [symbol, profile] of Object.entries(catalog.taxAssumptions)) {
    requireThat(seen.has(symbol), `unknown tax-profile symbol ${symbol}`);
    for (const required of ['divYield', 'qualifiedPct', 'capGainDistPct']) requireThat(own(profile, required), `missing ${required} for ${symbol}`);
    for (const [key, value] of Object.entries(profile)) {
      requireThat(numeric.has(key) ? Number.isFinite(value) && value >= 0 && value <= 100 : flags.has(key) && typeof value === 'boolean', `invalid ${symbol} tax assumption ${key}`);
    }
  }
  requireThat(Array.isArray(catalog.washSaleReviewGroups), 'missing wash-sale review groups');
  for (const group of catalog.washSaleReviewGroups) {
    requireThat(Array.isArray(group) && group.length > 1 && new Set(group).size === group.length && group.every(s => seen.has(s)), 'invalid wash-sale review group');
  }
  return catalog;
}
function loadCatalog() { return validateCatalog(JSON.parse(fs.readFileSync(path.join(root, 'data/instruments.json'), 'utf8'))); }
// Escape HTML delimiters even inside strings: no catalog entry can close the script.
const inlineJSON = value => JSON.stringify(value).replace(/</g, '\\u003c').replace(/\u2028/g, '\\u2028').replace(/\u2029/g, '\\u2029');
function catalogScript(catalog = loadCatalog()) {
  validateCatalog(catalog);
  const map = Object.fromEntries(catalog.instruments.map(r => [r.symbol, r.assetClass]));
  const notes = Object.fromEntries(catalog.instruments.filter(r => r.reviewNote).map(r => [r.symbol, r.reviewNote]));
  const names = catalog.enabledFields.includes('name') ? Object.fromEntries(catalog.instruments.filter(r => r.name).map(r => [r.symbol, r.name])) : {};
  return `// Embedded offline catalog. Edit data/instruments.json, then rebuild.\nconst US_TOTAL_SPLIT = ${inlineJSON(catalog.usTotalSplit)};\nconst SEED_MAP = ${inlineJSON(map)};\nconst SEED_MAP_EXT = {}; // Compatibility with the diagnostic console API.\nconst INSTRUMENT_REVIEW_NOTES = ${inlineJSON(notes)};\nconst INSTRUMENT_NAMES = ${inlineJSON(names)};\nconst SEED_TAX_DATA = ${inlineJSON(catalog.taxAssumptions)};\nconst WASH_CLONES = ${inlineJSON(catalog.washSaleReviewGroups)};`;
}
function readApp() {
  const source = fs.readFileSync(path.join(root, 'app.html'), 'utf8');
  requireThat(source.split(marker).length === 2, 'expected exactly one build marker in app.html');
  return source.replace(marker, () => catalogScript());
}
module.exports = { loadCatalog, validateCatalog, coverage, catalogScript, readApp };
